import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import axios from "axios";

const Home: NextPage = () => {
    const BASE_URL = "https://61d3de35b4c10c001712baeb.mockapi.io";

    const [data, setData] = React.useState<any[]>([]);

    // console.log(data);

    const [form, setForm] = React.useState({
        name: "",
        job: "",
        address: "",
    });

    const [button, setButton] = React.useState("Simpan");
    const [id, setId] = React.useState(null);
    const [isError, setIsError] = React.useState(false);
    const [isLoading, setIsLoading] = React.useState(false);

    const validate = (e: any) => {
        const name = e.target.value;
        setForm({ ...form, name: name });
        if (name.length < 5) {
            setIsError(true);
        } else {
            setIsError(false);
        }
    };

    const getData = async () => {
        const response = await axios.get(`${BASE_URL}/users`);
        setData(response.data);
    };

    const onSubmit = async (id: any) => {
        if (button === "Simpan") {
            setIsLoading(true);
            const response = await axios.post(`${BASE_URL}/users`, form);
            setIsLoading(false);
            setForm({
                name: "",
                job: "",
                address: "",
            });
            getData();
        } else {
            const response = await axios.put(`${BASE_URL}/users/${id}`, form);
            setId(null);
            setForm({
                name: "",
                job: "",
                address: "",
            });
            getData();
        }
    };

    const onSelect = (selectedUser: any) => {
        setButton("Update");
        setForm({
            name: selectedUser.name,
            job: selectedUser.job,
            address: selectedUser.address,
        });
        setId(selectedUser.id);
    };

    const onDelete = async (id: any) => {
        if (confirm("Apakah anda yakin?") == true)
            await axios.delete(`${BASE_URL}/users/${id}`);
        getData();
    };

    React.useEffect(() => {
        getData();
    }, []);

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="container mx-auto mt-10">
                <h1 className="font-poppins text-2xl">Handle Form</h1>
                {/* Card */}
                <div className="bg-white w-full mt-2 rounded-lg shadow-lg p-6">
                    <h1 className="text-center font-poppins font-bold text-2xl">
                        Form
                    </h1>
                    <div className="flex flex-col mt-2">
                        <label>Nama</label>
                        <input
                            type="text"
                            placeholder="Masukkan Nama Anda"
                            className="border-2 rounded-md mt-1 px-4 py-2 "
                            value={form.name}
                            onChange={(e) => validate(e)}
                        />
                        {isError ? (
                            <small className="text-red-600 text-xs">
                                Nama harus 5 karakter
                            </small>
                        ) : null}
                    </div>
                    <div className="flex flex-col mt-2">
                        <label>Pekerjaan</label>
                        <input
                            type="text"
                            placeholder="Masukkan Pekerjaan Anda"
                            className="border-2 rounded-md mt-1 px-4 py-2"
                            value={form.job}
                            onChange={(e) =>
                                setForm({ ...form, job: e.target.value })
                            }
                        />
                    </div>
                    <div className="flex flex-col mt-2">
                        <label>Alamat</label>
                        <textarea
                            placeholder="Masukkan Alamat Anda"
                            className="border-2 rounded-md mt-1 px-4 py-2"
                            value={form.address}
                            onChange={(e) =>
                                setForm({ ...form, address: e.target.value })
                            }
                        ></textarea>
                    </div>
                    <div className="flex flex-col mt-4">
                        {isLoading ? (
                            <button
                                className="bg-gray-500 rounded-md py-2 font-poppins text-white"
                                onClick={() => onSubmit(id)}
                            >
                                {button}
                            </button>
                        ) : (
                            <button
                                className="bg-blue-500 rounded-md py-2 font-poppins text-white"
                                onClick={() => onSubmit(id)}
                            >
                                {button}
                            </button>
                        )}
                    </div>
                </div>

                {/* List */}
                <div className="my-10">
                    <h1 className="font-poppins text-2xl">Daftar User</h1>
                    <div className="grid grid-cols-4 gap-3 mt-2">
                        {data.length > 0 ? (
                            data.map((item, index) => {
                                return (
                                    <div
                                        key={index}
                                        className="bg-white shadow-lg rounded-md p-4"
                                    >
                                        <h2 className="font-poppins text-xl">
                                            {item.name}
                                        </h2>
                                        <p className="font-poppins text-base">
                                            {item.job}
                                        </p>
                                        <p className="font-poppins text-base">
                                            {item.address}
                                        </p>
                                        <div>
                                            <button
                                                className="bg-blue-700 rounded-md py-1 px-2 font-poppins text-white mt-2 mr-2"
                                                onClick={() => onSelect(item)}
                                            >
                                                Edit
                                            </button>
                                            <button
                                                className="bg-red-700 rounded-md py-1 px-2 font-poppins text-white mt-2"
                                                onClick={() =>
                                                    onDelete(item.id)
                                                }
                                            >
                                                Delete
                                            </button>
                                        </div>
                                    </div>
                                );
                            })
                        ) : (
                            <div className="col-span-4 text-center">
                                <p>Data Tidak Ada</p>
                            </div>
                        )}
                    </div>
                </div>
            </main>
        </div>
    );
};

export default Home;
